[project]
name = "pysourcecraft"
version = "0.1.0"
description = "SourceCraft API-client"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.15.2",
    "ty>=0.0.18",
]
[tool.ruff]
cache-dir = ".cache"
