"""Pydantic models for SourceCraft API."""

from pysourcecraft.models.base import (
    APIError,
    BaseModel,
    ErrorResponse,
    PaginatedResponse,
    PaginationParams,
)
from pysourcecraft.models.cicd import (
    Artifact,
    Pipeline,
    PipelineJob,
    PipelineStage,
    PipelineStatus,
    Workflow,
    WorkflowConclusion,
    WorkflowEvent,
    WorkflowJob,
    WorkflowJobStep,
    WorkflowRun,
    WorkflowState,
)
from pysourcecraft.models.issues import (
    AttachmentEmbedded,
    CreateIssueRequest,
    Issue,
    IssueComment,
    IssueCommentEmbedded,
    IssueEvent,
    IssueFilters,
    IssueStatus,
    IssueVisibility,
    Label,
    LabelEmbedded,
    MilestoneEmbedded,
    Priority,
    PullRequestEmbedded,
    ReactionCount,
    StatusType,
    UpdateIssueRequest,
    UserEmbedded,
)
from pysourcecraft.models.milestones import (
    CreateMilestoneRequest,
    Milestone,
    MilestoneState,
    UpdateMilestoneRequest,
)
from pysourcecraft.models.pull_requests import (
    CreatePullRequestRequest,
    MergePullRequestRequest,
    PRBranch,
    PRCheck,
    PRCheckState,
    PRFilters,
    PRMergeMethod,
    PRReview,
    PRReviewState,
    PRState,
    PRUser,
    PullRequest,
    UpdatePullRequestRequest,
)
from pysourcecraft.models.repositories import (
    CloneURL,
    CreateRepositoryRequest,
    Image,
    Language,
    Link,
    LinkType,
    ListOrganizationRepositoriesResponse,
    OrganizationEmbedded,
    RepoBranch,
    RepoLanguage,
    RepoLicense,
    RepoOwner,
    RepoPermission,
    RepoTag,
    RepoTemplate,
    RepoVisibility,
    Repository,
    RepositoryCounters,
    RepositoryEmbedded,
    UpdateRepositoryRequest,
)
from pysourcecraft.models.releases import (
    CreateReleaseRequest,
    Release,
    ReleaseAsset,
    ReleaseAuthor,
    ReleaseState,
    UpdateReleaseRequest,
)
from pysourcecraft.models.users import (
    OrgMembership,
    Organization,
    Plan,
    User,
    UserType,
)

__all__ = [
    # Base
    "BaseModel",
    "PaginationParams",
    "PaginatedResponse",
    "ErrorResponse",
    "APIError",
    # Issues
    "Issue",
    "IssueStatus",
    "IssueVisibility",
    "Priority",
    "StatusType",
    "Label",
    "LabelEmbedded",
    "MilestoneEmbedded",
    "PullRequestEmbedded",
    "UserEmbedded",
    "ReactionCount",
    "AttachmentEmbedded",
    "IssueComment",
    "IssueCommentEmbedded",
    "IssueEvent",
    "CreateIssueRequest",
    "UpdateIssueRequest",
    "IssueFilters",
    # Pull Requests
    "PullRequest",
    "PRState",
    "PRMergeMethod",
    "PRReviewState",
    "PRCheckState",
    "PRBranch",
    "PRUser",
    "PRReview",
    "PRCheck",
    "CreatePullRequestRequest",
    "UpdatePullRequestRequest",
    "MergePullRequestRequest",
    "PRFilters",
    # Repositories
    "Repository",
    "RepoVisibility",
    "RepoPermission",
    "RepoTemplate",
    "RepoLanguage",
    "RepoOwner",
    "RepoLicense",
    "RepoBranch",
    "RepoTag",
    "CreateRepositoryRequest",
    "UpdateRepositoryRequest",
    "ListOrganizationRepositoriesResponse",
    # Repository nested models
    "CloneURL",
    "Language",
    "RepositoryCounters",
    "Image",
    "Link",
    "LinkType",
    "OrganizationEmbedded",
    "RepositoryEmbedded",
    # Milestones
    "Milestone",
    "MilestoneState",
    "CreateMilestoneRequest",
    "UpdateMilestoneRequest",
    # Releases
    "Release",
    "ReleaseState",
    "ReleaseAsset",
    "ReleaseAuthor",
    "CreateReleaseRequest",
    "UpdateReleaseRequest",
    # Users
    "User",
    "UserType",
    "Plan",
    "Organization",
    "OrgMembership",
    # CI/CD
    "WorkflowRun",
    "WorkflowState",
    "WorkflowConclusion",
    "WorkflowEvent",
    "WorkflowJob",
    "WorkflowJobStep",
    "Workflow",
    "Pipeline",
    "PipelineStatus",
    "PipelineStage",
    "PipelineJob",
    "Artifact",
]
